node {
  stage "Prepare environment"
  checkout scm

  dir("demo_app") {
    def image = docker.build "hello_world"

    image.inside {
      stage "Build application"
      sh "make"

      stage "Archive artifacts"
      archiveArtifacts "hello_world" 
    }
  }
}
